server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  application:
    name: user-micro # or api-gateway, etc.

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
